### PR TITLE
Prevent Parser from Panicking on Import Into Analyzed DB

### PR DESCRIPTION
**Pull request by Zalgo2462**
Added more granular locking to parser, prevent panic when importing data into an already analyzed dataset.

Establishes base line behavior for issue #133

### CODE REVIEW

**Comment by Zalgo2462** [comment]
I have tested this, but I would like someone else to test it as well.

**Comment by SamuelCarroll** [comment]
I'm on it!

**Comment by SamuelCarroll** [comment]
Just tested (and after a couple hiccups) it looks good! I'll have a look at the code too

**Comment by SamuelCarroll** [comment]
Looks good to me

**Pull request merged**
